DB_URL=${DB_URL:jdbc:postgresql://localhost:5432/card-application-oris}
DB_USER=${DB_USER:card-application}
DB_PASSWORD=${DB_PASSWORD:123456}

API.DOCUMENTS=${API_DOCUMENTS:http://185.221.160.131/api/documents}
API.USERS=${API_USERS:http://104.128.137.40/api/v1/users/}
API.TRANSFERS=${API_TRANSFERS:http://26.122.215.84:8083/api/v1/transfers/}